---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: 12

platforms:
  - name: centos-7.1
  - name: ubuntu-14.04
  - name: windows-2012r2

suites:
  - name: default
    run_list:
      - geckodriver_test::default
      - geckodriver_test::packages
    attributes:
